# Generated by Django 4.2 on 2025-04-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCrews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PILOT', 'Pilot'), ('COPILOT', 'Co-Pilot'), ('FLIGHT_ATTENDANT', 'Flight Attendant'), ('ENGINEER', 'Flight Engineer')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('CAN_REQ', 'Cancellation Request'), ('CAN_REJ', 'Rejected Cancellation Request'), ('CAN', 'Canceled')], default='SUCCESS', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.crewmember')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('airline_name', models.CharField(max_length=200)),
                ('airline_code', models.CharField(max_length=50)),
                ('airline_type', models.CharField(max_length=20)),
                ('flight_date', models.DateTimeField()),
                ('arrive_date', models.DateTimeField()),
                ('flight_time', models.CharField(max_length=20)),
                ('flight_permit', models.CharField(choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('ATPL', 'Airline Transport Pilot License'), ('HPL', 'Helicopter Pilot License'), ('GPL', 'Glider Pilot License')], max_length=10)),
                ('aircraft_type', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress')], default='SCHEDULED', max_length=20)),
                ('crew_members', models.ManyToManyField(through='flights.FlightCrews', to='appuser.crewmember')),
            ],
        ),
        migrations.AddField(
            model_name='flightcrews',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flights'),
        ),
        migrations.AlterUniqueTogether(
            name='flightcrews',
            unique_together={('flight', 'crew_member')},
        ),
    ]
