# Generated by Django 4.2 on 2025-04-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='booked_seats',
        ),
    ]
