# Generated by Django 4.2 on 2025-04-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flights_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='aircraft_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
