# Generated by Django 5.2 on 2025-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flights_aircraft_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcrews',
            name='role',
            field=models.CharField(choices=[('PI', 'Pilot'), ('CO-PI', 'Co-Pilot'), ('FL-EN', 'Flight Engineer'), ('FL-ATE', 'Flight Attendant')], max_length=20),
        ),
    ]
