# Generated by Django 4.2.6 on 2025-07-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
        ('flights', '0004_alter_flightcrews_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.crewmember')),
            ],
        ),
    ]
