# Generated by Django 4.2.6 on 2025-07-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flighthours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightHours',
        ),
    ]
