# Generated by Django 4.2.6 on 2025-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='flight_permit',
            field=models.CharField(blank=True, choices=[('ATPL', 'Airline Transport Pilot License'), ('CPL', 'Commercial Pilot License'), ('GPL', 'Glider Pilot License'), ('HPL', 'Helicopter Pilot License'), ('PPL', 'Private Pilot License')], max_length=10, null=True),
        ),
    ]
