# Generated by Django 4.2.6 on 2025-07-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_crewmember_flight_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewmember',
            name='flight_permit',
        ),
    ]
